package net.cnbec.catering.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.cnbec.catering.db.entity.PrinterEntity;

import net.cnbec.catering.db.PrinterEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig printerEntityDaoConfig;

    private final PrinterEntityDao printerEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        printerEntityDaoConfig = daoConfigMap.get(PrinterEntityDao.class).clone();
        printerEntityDaoConfig.initIdentityScope(type);

        printerEntityDao = new PrinterEntityDao(printerEntityDaoConfig, this);

        registerDao(PrinterEntity.class, printerEntityDao);
    }
    
    public void clear() {
        printerEntityDaoConfig.clearIdentityScope();
    }

    public PrinterEntityDao getPrinterEntityDao() {
        return printerEntityDao;
    }

}
