package net.cnbec.catering.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import net.cnbec.catering.db.entity.PrinterEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRINTER_ENTITY".
*/
public class PrinterEntityDao extends AbstractDao<PrinterEntity, Long> {

    public static final String TABLENAME = "PRINTER_ENTITY";

    /**
     * Properties of entity PrinterEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Ip = new Property(1, String.class, "ip", false, "IP");
    }


    public PrinterEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PrinterEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRINTER_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"IP\" TEXT);"); // 1: ip
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRINTER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PrinterEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(2, ip);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PrinterEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(2, ip);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public PrinterEntity readEntity(Cursor cursor, int offset) {
        PrinterEntity entity = new PrinterEntity( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // ip
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PrinterEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setIp(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PrinterEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PrinterEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PrinterEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
