platform :ios, '10.0'

target 'LiZaJiao' do

pod 'AFNetworking', '~> 2.4.1'
pod 'SVProgressHUD', '~> 1.1.2'
pod 'Masonry', '~> 0.6'
#pod 'SDWebImage', '~> 3.5'
pod 'SDWebImage', '>= 5.0.0'
pod 'YYImage'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'AxcAE_TabBar'
pod 'CMPageTitleView'
pod 'ZBarSDK', '~> 1.3.1'
pod 'TZImagePreviewController'
pod "SKFPicPreview"
pod 'TFPopup'
pod 'EasyShowView','~>2.1'
pod 'UITextView+Placeholder'

pod 'Bugly'

#pod 'WSDatePickerView', '~> 1.0'

##################加入代码##################
#    post_install do |installer|
#        installer.pods_project.targets.each do |target|
#            target.build_configurations.each do |config|
#                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] ='8.0'
#            end
#        end
#    end
##################加入代码##################

end
